- id: '1703771388622'
  alias: +temp
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_button.temp
  condition: []
  action:
  - service: mqtt.publish
    data:
      qos: '0'
      topic: IntexSpa/Cmd increase
      payload: '1'
  - service: mqtt.publish
    data:
      qos: '0'
      topic: '"IntexSpa/Cmd increase"'
      payload: '0'
  mode: single
- id: '1703776065215'
  alias: -temp
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_button.temp_2
  condition: []
  action:
  - service: mqtt.publish
    data:
      qos: '0'
      topic: IntexSpa/Cmd decrease
      payload: '1'
  mode: single
- id: '1703786594023'
  alias: Chlor Toggle
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_button.chlor_on_off_toggle
  condition: []
  action:
  - service: mqtt.publish
    data:
      qos: '0'
      topic: IntexSpa/Cmd sanitizer on off
      payload: '1'
  mode: single
- id: '1703786754661'
  alias: Filter Toggle
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_button.filter_on_off_toggle
  condition: []
  action:
  - service: mqtt.publish
    data:
      qos: '0'
      topic: IntexSpa/Cmd water filter on off
      payload: '1'
  mode: single
- id: '1703845936685'
  alias: Stoßchloren
  description: ''
  trigger:
  - platform: state
    entity_id:
    - schedule.timer_stosschloren
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: mqtt.publish
    data:
      qos: '0'
      topic: IntexSpa/Cmd sanitizer on off
      payload: '1'
  mode: single
