- id: '1703771388622'
  alias: +temp
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_button.temp
  condition: []
  action:
  - service: mqtt.publish
    data:
      qos: '0'
      topic: IntexSpa/Cmd increase
      payload: '1'
  mode: single
- id: '1703776065215'
  alias: -temp
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_button.temp_2
  condition: []
  action:
  - service: mqtt.publish
    data:
      qos: '0'
      topic: IntexSpa/Cmd decrease
      payload: '1'
  mode: single
- id: '1703865754569'
  alias: ESP Init
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_button.esp_init
  condition: []
  action:
  - service: mqtt.publish
    data:
      qos: '0'
      payload: reset
      topic: IntexSpa/Cmd Reset ESP
  mode: single
- id: '1703878371023'
  alias: MQTT Init after reboot
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: mqtt.publish
    data:
      qos: 0
      topic: IntexSpa/Cmd Reset ESP
      payload: reset
  mode: single
- id: '1703885703298'
  alias: Filtern
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_select.filter_timer
  condition: []
  action:
  - service: mqtt.publish
    data:
      qos: '0'
      topic: IntexSpa/Cmd water filter time
      payload: '{{ states(''input_select.filter_timer'') }}'
  mode: single
- id: '1703926180118'
  alias: Chlorem
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_select.chlor_timer
  condition: []
  action:
  - service: mqtt.publish
    data:
      qos: '0'
      topic: IntexSpa/Cmd Sanitizer time
      payload: '{{ states(''input_select.chlor_timer'') }}'
  mode: single
- id: '1703936592564'
  alias: Filtern Laufzeit Sync
  description: ''
  trigger:
  - platform: mqtt
    topic: IntexSpa/filter setup time
  condition: []
  action:
  - service: input_select.select_option
    target:
      entity_id: input_select.filter_timer
    data:
      option: '{{ trigger.payload }}'
  mode: single
- id: '1703937012696'
  alias: Chloren Laufzeit Sync
  description: ''
  trigger:
  - platform: mqtt
    topic: IntexSpa/Sanitizer setup time
  condition: []
  action:
  - service: input_select.select_option
    target:
      entity_id: input_select.chlor_timer
    data:
      option: '{{ trigger.payload }}'
  mode: single
- id: '1703940465725'
  alias: Stoßchloren
  description: ''
  trigger:
  - platform: state
    entity_id:
    - schedule.stosschloren_zeitplan
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.stosschloren
    state: 'on'
  action:
  - service: mqtt.publish
    data:
      qos: '0'
      topic: IntexSpa/Cmd sanitizer on off
      payload: '1'
  - service: mqtt.publish
    data:
      qos: '0'
      topic: IntexSpa/Cmd Sanitizer time
      payload: '8'
  mode: single
