- id: '1703771388622'
  alias: +temp
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_button.temp
  condition: []
  action:
  - service: mqtt.publish
    data:
      qos: '0'
      topic: IntexSpa/Cmd increase
      payload: '1'
  mode: single
- id: '1703776065215'
  alias: -temp
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_button.temp_2
  condition: []
  action:
  - service: mqtt.publish
    data:
      qos: '0'
      topic: IntexSpa/Cmd decrease
      payload: '1'
  mode: single
- id: '1703865754569'
  alias: ESP Init
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_button.esp_init
  condition: []
  action:
  - service: mqtt.publish
    data:
      qos: '0'
      payload: reset
      topic: IntexSpa/Cmd Reset ESP
  mode: single
- id: '1703878371023'
  alias: MQTT Init after reboot
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: mqtt.publish
    data:
      qos: 0
      topic: IntexSpa/Cmd Reset ESP
      payload: reset
  mode: single
- id: '1703885703298'
  alias: Filtern Laufzeit
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_select.filter_timer
  condition: []
  action:
  - service: mqtt.publish
    data:
      qos: '0'
      topic: IntexSpa/Cmd water filter time
      payload: '{{ states(''input_select.filter_timer'') }}'
  mode: single
- id: '1703926180118'
  alias: Chloren Laufzeit
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_select.chlor_timer
  condition: []
  action:
  - service: mqtt.publish
    data:
      qos: '0'
      topic: IntexSpa/Cmd Sanitizer time
      payload: '{{ states(''input_select.chlor_timer'') }}'
  mode: single
- id: '1703940465725'
  alias: Stoßchloren
  description: ''
  trigger:
  - platform: state
    entity_id:
    - schedule.stosschloren_zeitplan
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.stosschloren
    state: 'on'
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.stosschloren
      state: 'on'
  action:
  - service: mqtt.publish
    data:
      qos: '0'
      topic: IntexSpa/Cmd sanitizer on off
      payload: '1'
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: mqtt.publish
    data:
      qos: '0'
      topic: IntexSpa/Cmd Sanitizer time
      payload: '8'
  mode: single
- id: '1714503576338'
  alias: Filter On
  description: Filter On Timer
  trigger:
  - platform: state
    entity_id:
    - input_button.filter_on_off_timer
  condition: []
  action:
  - service: mqtt.publish
    data:
      qos: '0'
      topic: IntexSpa/Cmd water filter on off
      payload: '1'
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: mqtt.publish
    data:
      qos: '0'
      topic: IntexSpa/Cmd water filter time
      payload: '{{ states(''input_select.filter_timer'') }}'
  mode: single
- id: '1714572202493'
  alias: Filter Off
  description: Filter Aus
  trigger:
  - platform: state
    entity_id:
    - input_button.filter_off
  condition: []
  action:
  - service: mqtt.publish
    data:
      qos: '0'
      topic: IntexSpa/Cmd water filter on off
      payload: '0'
  mode: single
- id: '1714573589751'
  alias: Chlor On
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_button.chlor_on_off_timer
  condition: []
  action:
  - service: mqtt.publish
    data:
      qos: '0'
      topic: IntexSpa/Cmd sanitizer on off
      payload: '1'
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: mqtt.publish
    data:
      qos: '0'
      topic: IntexSpa/Cmd Sanitizer time
      payload: '{{ states(''input_select.chlor_timer'') }}'
  mode: single
- id: '1714574042006'
  alias: Chlor Off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_button.chlor_off
  condition: []
  action:
  - service: mqtt.publish
    data:
      qos: '0'
      topic: IntexSpa/Cmd sanitizer on off
      payload: '0'
  mode: single
