default_config:
          

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:

  climate:
    - name: "Intex_Actual_Temperature"
      modes: 
        - "heat"
        - "auto"
      current_temperature_topic: "IntexSpa/Actual Temperature"
      temperature_command_topic: "IntexSpa/Cmd Temperature Setpoint"
      temperature_state_topic: "IntexSpa/Temperature Setpoint"
    
      payload_on: "1"
      payload_off: "0"
      payload_available: "1"
      payload_not_available: "0"
    
      mode_command_topic: "IntexSpa/CMD HVAC Modeset"
      mode_state_topic: "IntexSpa/CMD HVAC Modeset"
      mode_state_template: >-
       {% set values = { '1':'auto', '2':'heat',  '3':'cool', '0':'off'} %}
          {{ values[value] if value in values.keys() else 'off' }}
      mode_command_template: >-
        {% set values = { 'auto':'4', 'heat':'5',  'cool':'3', 'off':'0'} %}
        {{ values[value] if value in values.keys() else '4' }}
  
      max_temp: "40"
      min_temp: "10"
    
  sensor:
    - state_topic: "IntexSpa/Actual Temperature"
      name: "Actual Temperature"
      unit_of_measurement: '°c'
      
    - state_topic: "IntexSpa/Error Number"
      name: "Status"
      unit_of_measurement: 'E'
      
    - state_topic: "IntexSpa/Temperature Setpoint"
      name: "Set Temp."
      unit_of_measurement: '°c'
    
    - state_topic: "IntexSpa/Communication with pump"
      name: "IntexSpa_Communication-with-pump"
    
    - state_topic: "payload"
      name: "Timer"
   
    - state_topic: "IntexSpa/heater state"
      name: "Intex/Heater Status"
    
    - state_topic: "IntexSpa/filter setup time"
      name: "IntexSpa/Filter Setup Timer"
    
    - state_topic: "IntexSpa/Sanitizer setup time"
      name: "IntexSpa/Desinfektion setup Timer"

  switch:
    - state_topic: "IntexSpa/Power on"
      command_topic: "IntexSpa/Cmd Power on off"
      payload_on: "1"
      payload_off: "0"
      name: "Intex_ON"
      
    - state_topic: "IntexSpa/filter on"
      command_topic: "IntexSpa/Cmd water filter on off"
      payload_on: "1"
      payload_off: "0"
      name: "Intex_Filter"
      
    - state_topic: "IntexSpa/Bubble on"
      command_topic: "IntexSpa/Cmd bubble on off"
      payload_on: "1"
      payload_off: "0"
      name: "Intex_Bubble"
    
    - state_topic: "IntexSpa/heater on"
      command_topic: "IntexSpa/Cmd heater on off"
      payload_on: "1"
      payload_off: "0"
      name: "Intex_Heat"
        
    - state_topic: "IntexSpa/Cmd decrease"
      command_topic: "IntexSpa/Cmd decrease"
      payload_on: "1"
      payload_off: "0"
      name: "Intex_decrease-"
    
    - state_topic: "IntexSpa/Cmd increase"
      command_topic: "IntexSpa/Cmd increase"
      payload_on: "1"
      payload_off: "0"
      name: "Intex_Increase+"
    
    - state_topic: "IntexSpa/Water jet on"
      command_topic: "IntexSpa/Cmd water jet on off"
      payload_on: "1"
      payload_off: "0"
      name: "Intex_Jets"
    
    - state_topic: "IntexSpa/Sanitizer on"
      command_topic: "IntexSpa/Cmd sanitizer on off"
      payload_on: "1"
      payload_off: "0"
      name: "Intex_Sanitizer"
    
    - state_topic: "IntexSpa/Cmd Reset ESP"
      command_topic: "IntexSpa/Cmd Reset ESP"
      payload_on: "reset"
      payload_off: " "
      name: "Reset ESP-script-switch"
    
    - command_topic: "IntexSpa/Cmd Farenheit Celsius"
      payload_on: "1"
      payload_off: "0"
      name: "Change Farenheit/Celsius"
    
    - command_topic: "IntexSpa/CMD HVAC Modeset"
      payload_on: "1"
      payload_off: "0"
      name: "Intex_HVAC_Tamplate_Switch"
    
    - state_topic: "IntexSpa/filter setup time"
      command_topic: "IntexSpa/Cmd water filter time"
      name: "Intex_Filter_Timer"
    
    - state_topic: "IntexSpa/Sanitizer setup time"
      command_topic: "IntexSpa/Cmd Sanitizer time"
      name: "Intex_Sanitizer_Timer"  

template:
  sensor:
    - name: "Intex Status Template"
      state: >-
        {% if is_state('sensor.status','0') %}
          OK
        {% else %}
          E 
          {{ states('sensor.status') }}
        {% endif %}  

    - name: "Intex Communication with pump - Template"
      state: >-
        {% if is_state('sensor.intexSpa_communication-with-pump','1') %}
          OK
        {% else %}
          Keine Verbindung
        {% endif %}
          
    - name: "Timer"
      state: >-
        {% if is_state('sensor.timer','-1') %}
          Aus
        {% else %}
           {{ states('sensor.timer') }} 
        {% endif %}
        
    - name: "SetTempTest"
      state: >-
        {% if is_state('IntexSpa/Temperature Setpoint',' ') %}
          Aus1
        {% else %}
           {{ states('IntexSpa/Temperature Setpoint') }} 
        {% endif %}
          
        
