
default_config:
          

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  sensor:
    - state_topic: "IntexSpa/Actual Temperature"
      unique_id: "ipoolactualtemp"
      name: "Actual Temperature"
      unit_of_measurement: '°c'
      
    - state_topic: "IntexSpa/Error Number"
      unique_id: "ipoolerrnum"
      name: "IntexSpa_Status"
      unit_of_measurement: 'E'
      
    - state_topic: "IntexSpa/Temperature Setpoint"
      unique_id: "ipoolsettemp"
      name: "Set Temp."
      unit_of_measurement: '°c'
    
    - state_topic: "IntexSpa/Communication with pump"
      unique_id: "ipoolcwp"
      name: "IntexSpa_Communication-with-pump"
   
    - state_topic: "IntexSpa/heater state"
      unique_id: "ipoolheaterstate"
      name: "Intex/Heater Status"
    
    - state_topic: "IntexSpa/filter setup time"
      unique_id: "ipoolfiltersetuptime"
      name: "IntexSpa/Filter Setup Timer"
      unit_of_measurement: 'min'
    
    - state_topic: "IntexSpa/Sanitizer setup time"
      unique_id: "ipoolchorsetuptime"
      name: "IntexSpa/Desinfektion setup Timer"
      unit_of_measurement: 'min'
      
    - state_topic: "IntexSpa/filter on"
      unique_id: "ipoolfilter"
      name: "Intex_Filter_Status"
      
    - state_topic: "IntexSpa/Sanitizer on"
      unique_id: "ipoolchlor"
      name: "Intex_Sanitizer_Status"

  switch:
    - state_topic: "IntexSpa/Power on"
      unique_id: "spoolpower"
      command_topic: "IntexSpa/Cmd Power on off"
      payload_on: "1"
      payload_off: "0"
      name: "Intex_ON"

    - state_topic: "IntexSpa/Bubble on"
      unique_id: "spoolbubble"
      command_topic: "IntexSpa/Cmd bubble on off"
      payload_on: "1"
      payload_off: "0"
      name: "Intex_Bubble"
    
    - state_topic: "IntexSpa/heater on"
      unique_id: "spoolheat"
      command_topic: "IntexSpa/Cmd heater on off"
      payload_on: "1"
      payload_off: "0"
      name: "Intex_Heat"
      
    - state_topic: "IntexSpa/filter on"
      command_topic: "IntexSpa/Cmd water filter on off"
      payload_on: "1"
      payload_off: "0"
      name: "Intex_Filter"
      
    - state_topic: "IntexSpa/Sanitizer on"
      command_topic: "IntexSpa/Cmd sanitizer on off"
      payload_on: "1"
      payload_off: "0"
      name: "Intex_Sanitizer"
        
    - state_topic: "IntexSpa/Water jet on"
      unique_id: "spooljet"
      command_topic: "IntexSpa/Cmd water jet on off"
      payload_on: "1"
      payload_off: "0"
      name: "Intex_Jets"
    
    - state_topic: "IntexSpa/Cmd Reset ESP"
      unique_id: "spoolespreset"
      command_topic: "IntexSpa/Cmd Reset ESP"
      payload_on: "reset"
      payload_off: " "
      name: "Reset ESP-script-switch"
    
    - command_topic: "IntexSpa/Cmd Farenheit Celsius"
      unique_id: "spoolsfc"
      payload_on: "1"
      payload_off: "0"
      name: "Change Farenheit/Celsius"
      
template:
  sensor:
    - name: "Intex Status Template"
      unique_id: "tpoolstatus"
      state: >
        {% if is_state('sensor.intexspa_status','0') %}
          OK
        {% else %}
          E 
          {{ states('sensor.intexspa_status') }}
        {% endif %} 

    - name: "Intex Communication with pump - Template"
      unique_id: "tpoolcwp"
      state: >-
        {% if is_state('sensor.intexspa_communication_with_pump','1') %}
          OK
        {% else %}
          Keine Verbindung
        {% endif %}
          
